#!/usr/bin/env python3
"""VPN-only host for passphrase-sealed LifeOS backups.

WHY IT EXISTS. A phone's graph backup must survive the phone. The archive is
already sealed with a key derived from the user's passphrase
(mobile/lib/core/security/passphrase_backup_sealer.dart), so what is stored
here is opaque to this service, to whoever runs it, and to anyone who reads
the disk. This is deliberately a dumb box of bytes: it never decrypts, and it
holds no key that could.

WHY NOT THE OTA HOST. `updates.lifeos.<domain>` is public, behind Cloudflare,
and gated by a static header. That is the right shape for signed APKs, which
are meant to be public artefacts. Personal data takes the other path: this
listens on the WireGuard address only, so backup traffic never leaves the
private network even though the payload could survive doing so.

Standard library only — the VPS carries no project virtualenv, and a backup
path that cannot start because a dependency failed to install is worse than
a plain one.
"""

from __future__ import annotations

import argparse
import hmac
import json
import os
import re
import sys
import tempfile
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

# Conservative on purpose: names are generated by the app, not typed by a user.
_SAFE_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
_DEFAULT_MAX_BYTES = 512 * 1024 * 1024


class BackupStore:
    """Filesystem store rooted at a single directory."""

    def __init__(self, root: Path, max_bytes: int = _DEFAULT_MAX_BYTES) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)
        self.max_bytes = max_bytes

    def path_for(self, name: str) -> Path:
        """Resolve a request name to a path inside the root, or refuse.

        Two independent checks: the name must match a strict pattern, AND the
        resolved path must still sit under the root. Either alone would very
        likely do; together they mean a mistake in one is not an escape.
        """
        if not _SAFE_NAME.match(name or "") or name in (".", ".."):
            raise ValueError(f"unsafe backup name: {name!r}")
        candidate = (self.root / name).resolve()
        if candidate.parent != self.root.resolve():
            raise ValueError(f"backup name escapes the store: {name!r}")
        return candidate

    def write(self, name: str, payload: bytes) -> Path:
        """Write atomically: a reader never sees a half-uploaded archive, and
        a failed upload leaves nothing that could later be restored as whole."""
        destination = self.path_for(name)
        handle, temporary = tempfile.mkstemp(dir=self.root, suffix=".part")
        try:
            with os.fdopen(handle, "wb") as stream:
                stream.write(payload)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, destination)
        except BaseException:
            Path(temporary).unlink(missing_ok=True)
            raise
        return destination

    def read(self, name: str) -> bytes | None:
        path = self.path_for(name)
        if not path.is_file():
            return None
        return path.read_bytes()

    def listing(self) -> list[dict]:
        entries = []
        for path in sorted(self.root.iterdir()):
            if not path.is_file() or path.suffix == ".part":
                continue
            stat = path.stat()
            entries.append(
                {
                    "name": path.name,
                    "sizeBytes": stat.st_size,
                    "modifiedAt": datetime.fromtimestamp(
                        stat.st_mtime, tz=timezone.utc
                    ).isoformat(),
                }
            )
        return entries


def make_handler(*, store: BackupStore, token: str):
    class Handler(BaseHTTPRequestHandler):
        server_version = "lifeos-backup-host/1"
        protocol_version = "HTTP/1.1"

        # ------------------------------------------------------------ replies
        def _send(self, status: HTTPStatus | int, payload: bytes, content_type: str):
            self.send_response(int(status))
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            if self.command != "HEAD":
                self.wfile.write(payload)

        def _json(self, status, body: dict):
            self._send(status, json.dumps(body).encode(), "application/json")

        def _authorised(self) -> bool:
            supplied = self.headers.get("X-LifeOS-Backup-Key", "")
            # compare_digest: the comparison time must not depend on how many
            # leading characters an attacker guessed correctly.
            return hmac.compare_digest(supplied, token)

        def _name_from(self, prefix: str) -> str | None:
            if not self.path.startswith(prefix):
                return None
            return self.path[len(prefix) :]

        # ----------------------------------------------------------- verbs
        def do_GET(self):  # noqa: N802 - BaseHTTPRequestHandler's contract
            if not self._authorised():
                return self._json(HTTPStatus.UNAUTHORIZED, {"error": "unauthorised"})

            if self.path.rstrip("/") == "/v1/backups":
                return self._json(HTTPStatus.OK, {"backups": store.listing()})

            name = self._name_from("/v1/backups/")
            if name is None:
                return self._json(HTTPStatus.NOT_FOUND, {"error": "no such route"})
            try:
                payload = store.read(name)
            except ValueError:
                return self._json(HTTPStatus.BAD_REQUEST, {"error": "bad name"})
            if payload is None:
                return self._json(HTTPStatus.NOT_FOUND, {"error": "no such backup"})
            return self._send(
                HTTPStatus.OK, payload, "application/octet-stream"
            )

        def do_PUT(self):  # noqa: N802
            if not self._authorised():
                return self._json(HTTPStatus.UNAUTHORIZED, {"error": "unauthorised"})

            name = self._name_from("/v1/backups/")
            if name is None:
                return self._json(HTTPStatus.NOT_FOUND, {"error": "no such route"})

            try:
                length = int(self.headers.get("Content-Length", "0"))
            except ValueError:
                return self._json(HTTPStatus.BAD_REQUEST, {"error": "bad length"})
            if length > store.max_bytes:
                # Refuse BEFORE reading the body, so an oversized upload cannot
                # fill the disk on its way to being rejected.
                return self._json(
                    HTTPStatus.REQUEST_ENTITY_TOO_LARGE,
                    {"error": "too large", "maxBytes": store.max_bytes},
                )

            try:
                store.path_for(name)
            except ValueError:
                return self._json(HTTPStatus.BAD_REQUEST, {"error": "bad name"})

            payload = self.rfile.read(length) if length else b""
            store.write(name, payload)
            return self._json(
                HTTPStatus.CREATED, {"name": name, "sizeBytes": len(payload)}
            )

        do_POST = do_PUT

        def log_message(self, fmt, *args):
            # Never log the path: backup names are user data. Method and status
            # are enough to see the service working.
            sys.stderr.write(
                f"{self.address_string()} {self.command} {args[1] if len(args) > 1 else '-'}\n"
            )

    return Handler


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--host",
        default="10.66.66.1",
        help="address to bind; defaults to the WireGuard address so the "
        "service is unreachable from the public interface",
    )
    parser.add_argument("--port", type=int, default=8099)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.home() / "lifeos-backups" / "mobile",
        help="directory holding the sealed archives",
    )
    parser.add_argument(
        "--max-bytes", type=int, default=_DEFAULT_MAX_BYTES, help="per-upload ceiling"
    )
    args = parser.parse_args(argv)

    token = os.environ.get("LIFEOS_BACKUP_KEY", "").strip()
    if len(token) < 32:
        parser.error(
            "LIFEOS_BACKUP_KEY must be set to at least 32 characters; refusing "
            "to expose a backup store behind a weak or empty key"
        )

    store = BackupStore(args.root, max_bytes=args.max_bytes)
    httpd = ThreadingHTTPServer((args.host, args.port), make_handler(store=store, token=token))
    sys.stderr.write(f"backup host listening on {args.host}:{args.port} -> {args.root}\n")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        httpd.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
