// Loading the word bank of the vocabulary placement.
//
// The bank is a bundled asset, generated by tool/english/build_vocab_bank.py
// from the CEFR-J and Octanove vocabulary profiles, ranked by wordfreq. It is
// data that ships inside the app, so the test runs offline and on every
// device, like everything else in LifeOS. Sources and licenses are in
// assets/english/NOTICE.md.
library;

import 'dart:convert';

import 'package:flutter/services.dart';

import '../domain/vocab_placement_session.dart';

const String kVocabBankAsset = 'assets/english/vocab_bank.json';

/// The only format this code understands. A newer asset should fail loudly
/// rather than be half-read into a wrong level.
const int kVocabBankVersion = 1;

VocabBank parseVocabBank(String source) {
  final json = _decode(source);
  final bands = json['bands'];
  if (bands is! List) throw const FormatException('"bands" is not a list');
  return VocabBank(
    bands: [for (final band in bands) _words(band, 'band')],
    pseudowords: _words(json['pseudowords'], 'pseudowords'),
  );
}

/// Words per band as declared by the generator. The scoring assumes
/// [kBandSize]; a test holds the shipped asset to it.
int vocabBankBandSize(String source) {
  final size = _decode(source)['bandSize'];
  if (size is! int) throw const FormatException('"bandSize" is not an int');
  return size;
}

Future<VocabBank> loadVocabBank(AssetBundle bundle) async =>
    parseVocabBank(await bundle.loadString(kVocabBankAsset));

Map<String, Object?> _decode(String source) {
  final json = jsonDecode(source);
  if (json is! Map<String, Object?>) {
    throw const FormatException('The word bank is not a JSON object');
  }
  if (json['version'] != kVocabBankVersion) {
    throw FormatException('Unsupported word bank version: ${json['version']}');
  }
  return json;
}

List<String> _words(Object? value, String what) {
  if (value is! List || value.any((word) => word is! String)) {
    throw FormatException('"$what" is not a list of words');
  }
  return List.unmodifiable(value.cast<String>());
}
