// The word bank the vocabulary placement ships with.
//
// The asset is generated by tool/english/build_vocab_bank.py. These tests hold
// it to the promises the scoring depends on: every band is exactly a thousand
// distinct words, no word is in two bands, and no invented word is real.
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lifeos/features/english/data/vocab_bank_asset.dart';
import 'package:lifeos/features/english/domain/vocab_placement_scoring.dart';
import 'package:lifeos/features/english/domain/vocab_placement_session.dart';

void main() {
  group('parsing a bank', () {
    test('reads bands in order and the invented words', () {
      final bank = parseVocabBank(
        '{"version": 1, "bandSize": 2, "bands": [["the", "and"], ["tree", '
        '"river"]], "pseudowords": ["dortily"]}',
      );

      expect(bank.bands, [
        ['the', 'and'],
        ['tree', 'river'],
      ]);
      expect(bank.pseudowords, ['dortily']);
    });

    test('refuses a version it does not understand', () {
      expect(
        () => parseVocabBank(
          '{"version": 2, "bandSize": 1, "bands": [], "pseudowords": []}',
        ),
        throwsFormatException,
      );
    });

    test('refuses a band that is not a list of words', () {
      expect(
        () => parseVocabBank(
          '{"version": 1, "bandSize": 1, "bands": [[1]], "pseudowords": []}',
        ),
        throwsFormatException,
      );
    });
  });

  group('the shipped bank', () {
    late VocabBank bank;
    late int bandSize;

    setUpAll(() {
      final source = File('assets/english/vocab_bank.json').readAsStringSync();
      bank = parseVocabBank(source);
      bandSize = vocabBankBandSize(source);
    });

    test('bands are the size the scoring multiplies by', () {
      expect(bandSize, kBandSize);
    });

    test('covers at least the 5000 words the CEFR level is based on', () {
      expect(bank.bands.length, greaterThanOrEqualTo(kXlexBands));
    });

    test('every band is a thousand distinct words, none in two bands', () {
      final seen = <String>{};
      for (final band in bank.bands) {
        expect(band.toSet(), hasLength(kBandSize));
        expect(seen.intersection(band.toSet()), isEmpty);
        seen.addAll(band);
      }
    });

    test('no invented word is a word of the bank', () {
      final real = {for (final band in bank.bands) ...band};

      expect(real.intersection(bank.pseudowords.toSet()), isEmpty);
    });

    test('has enough invented words for a full test without repeats', () {
      final perTest = bank.bands.length *
          (kPlacementWordsPerBand ~/ kRealWordsPerPseudoword);

      expect(bank.pseudowords.toSet().length, greaterThanOrEqualTo(perTest));
    });

    test('is declared as an asset, so the app can load it', () async {
      TestWidgetsFlutterBinding.ensureInitialized();

      final loaded = await loadVocabBank(rootBundle);
      expect(loaded.bands, hasLength(bank.bands.length));
    });
  });
}
