"""The crypto core of device sync, pinned by vectors before anything uses it.

WHY THIS FILE EXISTS AND WHY IT COMES FIRST.

Two independent implementations of one crypto format is the single biggest
correctness risk in device sync: this Python core and the Dart mirror in
`mobile/lib/core/sync/`. They must agree BYTE FOR BYTE on the mnemonic
encoding, on every HKDF derivation, and on the Ed25519 keypair derived from a
mailbox seed. If they drift, an envelope sealed on the laptop simply will not
open on the phone — and you find out with real data inside it.

The defence is `shared/sync-test-vectors/vectors.json`: fixed inputs and their
expected outputs, generated here and asserted by BOTH test suites. This file
is what makes that file trustworthy, so it lands before a single line of Dart
crypto exists (task 1a.6 blocks PR 1c).

WHAT IS DELIBERATELY NOT HERE. No passphrase. BIP-39's optional passphrase
would be a second secret to store, audit and lose — and the recovery contract
is that TWELVE WORDS restore everything. One secret, one ceremony.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from axi.sync import keys, phrase

# The official BIP-39 English wordlist, vendored rather than pulled from a
# package: the words ARE the format. A dependency that silently reorders or
# renormalises them would change every mnemonic this app has ever generated,
# and users would be locked out with no error to read.
_WORDLIST_SHA256 = "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda"

# From the canonical BIP-39 test vectors (Trezor's python-mnemonic
# `vectors.json`). Only the 128-bit entries: our scheme is 12 words, always.
_TREZOR_128BIT = [
    (
        "00000000000000000000000000000000",
        "abandon abandon abandon abandon abandon abandon abandon abandon "
        "abandon abandon abandon about",
    ),
    (
        "7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f",
        "legal winner thank year wave sausage worth useful legal winner "
        "thank yellow",
    ),
    (
        "80808080808080808080808080808080",
        "letter advice cage absurd amount doctor acoustic avoid letter "
        "advice cage above",
    ),
    (
        "ffffffffffffffffffffffffffffffff",
        "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong",
    ),
]


def test_vendored_wordlist_is_the_official_one_unmodified():
    """A wordlist that drifts is a silent, total loss of every existing phrase.

    Checked by content hash, not by word count: a list with the right 2048
    entries in the WRONG ORDER encodes different indices, produces different
    entropy for the same words, and would pass any length check.
    """
    raw = Path(phrase.WORDLIST_PATH).read_bytes()
    assert hashlib.sha256(raw).hexdigest() == _WORDLIST_SHA256, (
        "the vendored BIP-39 English wordlist does not match the official one; "
        "every phrase ever generated by LifeOS decodes against THIS file"
    )
    assert len(phrase.WORDS) == 2048
    assert phrase.WORDS[0] == "abandon"
    assert phrase.WORDS[-1] == "zoo"


@pytest.mark.parametrize(("entropy_hex", "mnemonic"), _TREZOR_128BIT)
def test_official_bip39_vectors_round_trip(entropy_hex: str, mnemonic: str):
    """Task 1a.3 — the canonical vectors, both directions."""
    entropy = bytes.fromhex(entropy_hex)

    assert phrase.encode(entropy) == mnemonic
    assert phrase.decode(mnemonic) == entropy


def test_a_mistyped_word_fails_the_checksum_before_any_derivation():
    """Task 1a.1 — reject early, never derive a wrong key from a typo.

    The failure mode this prevents: the user mistypes one word, we happily
    derive SOME key from it, and every envelope silently fails to open with no
    explanation. A checksum failure is a clear, actionable error; a wrong key
    is an unexplainable outage.
    """
    good = phrase.encode(bytes.fromhex("00000000000000000000000000000000"))
    # Swap the last word for another valid wordlist entry: every word is real,
    # only the checksum is wrong. A "are all the words in the list?" check
    # would wave this through.
    broken = " ".join(good.split()[:-1] + ["zoo"])

    with pytest.raises(phrase.InvalidPhrase):
        phrase.decode(broken)


def test_a_word_outside_the_list_is_rejected():
    good = phrase.encode(bytes.fromhex("80808080808080808080808080808080"))
    broken = " ".join(good.split()[:-1] + ["notaword"])

    with pytest.raises(phrase.InvalidPhrase):
        phrase.decode(broken)


def test_normalisation_accepts_what_a_human_actually_types():
    """Case, padding and repeated spaces are typing, not a different phrase."""
    canonical = phrase.encode(bytes.fromhex("7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f"))
    messy = "   " + canonical.upper().replace(" ", "   ") + "  \n"

    assert phrase.decode(messy) == phrase.decode(canonical)


def test_same_phrase_derives_identical_keys_every_time():
    """Task 1a.2 — determinism is the whole recovery contract.

    If this ever varies, entering the phrase on a new device produces a key
    that opens nothing, and the twelve words the user wrote on paper are
    worthless.
    """
    mnemonic = _TREZOR_128BIT[0][1]
    mailbox = "0123456789abcdef0123456789abcdef"

    first = keys.derive(phrase.decode(mnemonic))
    second = keys.derive(phrase.decode(mnemonic))

    assert first.root_key == second.root_key
    assert first.data_key == second.data_key
    assert len(first.root_key) == 32
    assert len(first.data_key) == 32
    # The root key must NOT be the raw entropy handed straight through.
    assert first.root_key != phrase.decode(mnemonic)
    # ...and the data key is derived FROM the root, not equal to it.
    assert first.data_key != first.root_key

    assert first.mailbox_auth_public(mailbox) == second.mailbox_auth_public(mailbox)
    assert len(first.mailbox_auth_public(mailbox)) == 32


def test_different_phrases_derive_different_keys():
    """Guards against a derivation that ignores its input entirely."""
    a = keys.derive(phrase.decode(_TREZOR_128BIT[0][1]))
    b = keys.derive(phrase.decode(_TREZOR_128BIT[1][1]))

    assert a.root_key != b.root_key
    assert a.data_key != b.data_key


def test_each_mailbox_gets_an_unlinkable_auth_key():
    """The relay must not be able to tell two mailboxes belong to one person.

    Per-mailbox auth keys are derived with the mailbox UUID as HKDF salt, so
    the relay sees one random-looking pubkey per mailbox and no way to group
    them. A single set-wide key would hand it the device-set map for free.
    """
    derived = keys.derive(phrase.decode(_TREZOR_128BIT[0][1]))

    one = derived.mailbox_auth_public("11111111111111111111111111111111")
    two = derived.mailbox_auth_public("22222222222222222222222222222222")

    assert one != two


def test_committed_vectors_match_what_the_code_produces_right_now():
    """The committed vector file is the contract; drift from it is the signal.

    `shared/sync-test-vectors/vectors.json` is read by the DART suite too. If
    someone changes a domain string, the wordlist or a KDF parameter and does
    not regenerate, this fails here — loudly, in the language that owns the
    format — instead of surfacing as an envelope the phone cannot open.

    Regenerate with:
        python -m axi.sync.vectors > shared/sync-test-vectors/vectors.json
    """
    from axi.sync import vectors

    committed = Path(__file__).resolve().parents[2] / "shared" / "sync-test-vectors" / "vectors.json"
    assert committed.exists(), f"the shared vector file is missing at {committed}"

    assert committed.read_text(encoding="utf-8") == vectors.render(), (
        "the committed cross-language vectors no longer match this "
        "implementation. If the format change was intended, regenerate the "
        "file and expect the Dart suite to go red until it matches; if it was "
        "not, you have changed the wire format by accident"
    )


def test_the_vector_file_pins_the_wordlist_it_was_built_from():
    """A vector set is only meaningful alongside the wordlist that produced it."""
    import json

    committed = Path(__file__).resolve().parents[2] / "shared" / "sync-test-vectors" / "vectors.json"
    data = json.loads(committed.read_text(encoding="utf-8"))

    assert data["wordlist_sha256"] == _WORDLIST_SHA256
    assert data["format_version"] == 1
    # Honesty about coverage: the envelope is not built yet, and the file says
    # so rather than implying the whole format is pinned.
    assert "envelope-framing" in data["not_yet_covered"]
