// The Dart half of the crypto core, held to the SAME bytes as the Python half.
//
// WHY THIS FILE IS THE POINT OF SLICE 1C. LifeOS now has two independent
// implementations of one crypto format: `axi/src/axi/sync/` and this. If they
// drift by a single byte — a different HKDF `info` string, a different word
// order, a different Ed25519 seed derivation — an envelope sealed on the
// laptop will not open on the phone. You would find that out with real data
// inside it, and the only symptom would be "sync does nothing".
//
// The defence is `shared/sync-test-vectors/vectors.json`: fixed inputs and
// expected outputs, GENERATED BY PYTHON and asserted here. This suite reads
// that file. It does not recompute what the expected values "should" be — that
// would just be this implementation agreeing with itself.
//
// If this file goes red after a change to the Python side, that is the system
// working: the wire format changed and Dart has not caught up yet.
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart' show sha256;
import 'package:flutter_test/flutter_test.dart';
import 'package:lifeos/core/sync/bip39_wordlist.dart';
import 'package:lifeos/core/sync/keys.dart';
import 'package:lifeos/core/sync/phrase.dart';

/// The same hash the Python suite asserts. Two vendored copies of the wordlist,
/// one contract between them.
const String _wordlistSha256 =
    '2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda';

Map<String, dynamic> _loadVectors() {
  // Tests run with `mobile/` as the working directory; the shared file lives
  // one level up, deliberately outside either language's tree so neither owns
  // it.
  final file = File('../shared/sync-test-vectors/vectors.json');
  expect(
    file.existsSync(),
    isTrue,
    reason: 'the shared cross-language vectors are missing at ${file.path}. '
        'They are generated by `python -m axi.sync.vectors` and MUST exist '
        'before any Dart crypto is trusted',
  );
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

void main() {
  test('the vendored wordlist is byte-identical to the Python copy', () {
    // Hashed as the newline-separated text file the Python side reads, so the
    // two copies are provably the same list in the same order — not merely two
    // lists that happen to be 2048 words long.
    final asFile = '${kBip39English.join('\n')}\n';
    expect(sha256.convert(utf8.encode(asFile)).toString(), _wordlistSha256);
    expect(kBip39English.length, 2048);
    expect(kBip39English.first, 'abandon');
    expect(kBip39English.last, 'zoo');
  });

  test('the vector file is the version this implementation understands', () {
    final vectors = _loadVectors();

    expect(
      vectors['format_version'],
      1,
      reason: 'the shared vectors declare a format this Dart implementation '
          'does not implement — update it rather than loosening this check',
    );
    expect(vectors['wordlist_sha256'], _wordlistSha256);
  });

  test('every Python vector reproduces exactly in Dart', () async {
    final vectors = _loadVectors();
    final cases = (vectors['cases'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);

    for (final c in cases) {
      final entropyHex = c['entropy'] as String;
      final entropy = _hexToBytes(entropyHex);
      final where = 'entropy $entropyHex';

      // 1. mnemonic, both directions.
      expect(encodePhrase(entropy), c['mnemonic'], reason: 'encode: $where');
      expect(
        _bytesToHex(decodePhrase(c['mnemonic'] as String)),
        entropyHex,
        reason: 'decode: $where',
      );

      // 2. the key hierarchy.
      final derived = await deriveSyncKeys(entropy);
      expect(_bytesToHex(derived.rootKey), c['root_key'], reason: 'RK: $where');
      expect(_bytesToHex(derived.dataKey), c['data_key'], reason: 'DK: $where');

      // 3. per-mailbox Ed25519 auth keys.
      final mailboxes = (c['mailbox_auth_public'] as Map).cast<String, dynamic>();
      for (final entry in mailboxes.entries) {
        final pub = await derived.mailboxAuthPublic(entry.key);
        expect(
          _bytesToHex(pub),
          entry.value,
          reason: 'mailbox ${entry.key}: $where',
        );
      }
    }
  });

  test('a mistyped word is rejected before any key is derived', () {
    final vectors = _loadVectors();
    final good = (vectors['cases'] as List).first['mnemonic'] as String;
    final words = good.split(' ');
    // Every word real, only the checksum wrong — the common case, and the one
    // a "are all the words in the list?" check waves through.
    final broken = ([...words.take(words.length - 1), 'zoo']).join(' ');

    expect(() => decodePhrase(broken), throwsA(isA<InvalidPhrase>()));
  });

  test('a word outside the list is rejected', () {
    final vectors = _loadVectors();
    final good = (vectors['cases'] as List).first['mnemonic'] as String;
    final words = good.split(' ');
    final broken = ([...words.take(words.length - 1), 'notaword']).join(' ');

    expect(() => decodePhrase(broken), throwsA(isA<InvalidPhrase>()));
  });

  test('case and spacing are normalised the same way Python normalises them', () {
    final vectors = _loadVectors();
    final canonical = (vectors['cases'] as List)[1]['mnemonic'] as String;
    final messy = '   ${canonical.toUpperCase().replaceAll(' ', '   ')}  \n';

    expect(_bytesToHex(decodePhrase(messy)), _bytesToHex(decodePhrase(canonical)));
  });

  test('the wrong number of words is rejected', () {
    expect(() => decodePhrase('abandon abandon about'), throwsA(isA<InvalidPhrase>()));
  });
}

List<int> _hexToBytes(String hex) => [
      for (var i = 0; i < hex.length; i += 2)
        int.parse(hex.substring(i, i + 2), radix: 16),
    ];

String _bytesToHex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
