//! AI Security Daemon (Fase Y)
//!
//! Process and network monitoring with anomaly detection.
//! Scans for suspicious activity: crypto-mining ports, unexpected processes,
//! file integrity changes, and resource abuse.

use anyhow::Result;
use chrono::{DateTime, Utc};
use log::{debug, warn};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fs;
use std::process::Command;

/// Severity levels for security alerts.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

/// A security alert generated by a scan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityAlert {
    pub severity: AlertSeverity,
    pub category: String,
    pub message: String,
    pub timestamp: DateTime<Utc>,
    pub process: Option<String>,
}

/// Baseline statistics for a known process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessBaseline {
    pub pid: u32,
    pub name: String,
    pub avg_cpu: f64,
    pub avg_mem: f64,
    pub avg_net_bytes: u64,
    pub sample_count: u64,
}

/// Known crypto-mining pool ports.
const MINING_PORTS: &[u16] = &[3333, 4444, 5555, 8333, 14444];

/// Default critical files to monitor for integrity.
const DEFAULT_INTEGRITY_PATHS: &[&str] = &["/etc/passwd", "/etc/shadow", "/etc/sudoers"];

/// AI Security daemon that monitors processes, network, and file integrity.
#[derive(Debug)]
pub struct SecurityDaemon {
    /// Per-process-name baselines (keyed by process name).
    baselines: HashMap<String, ProcessBaseline>,
    /// Stored SHA-256 hashes for file integrity checks.
    file_hashes: HashMap<String, String>,
    /// Whitelisted listening ports.
    port_whitelist: Vec<u16>,
}

impl SecurityDaemon {
    /// Create a new security daemon with empty baselines.
    pub fn new() -> Self {
        Self {
            baselines: HashMap::new(),
            file_hashes: HashMap::new(),
            // Common whitelisted ports: SSH, HTTP API, llama-server
            port_whitelist: vec![22, 8080, 8081, 8082],
        }
    }

    /// Add a port to the whitelist of expected listening ports.
    pub fn whitelist_port(&mut self, port: u16) {
        if !self.port_whitelist.contains(&port) {
            self.port_whitelist.push(port);
        }
    }

    // -----------------------------------------------------------------------
    // Process scanning
    // -----------------------------------------------------------------------

    /// Scan running processes by reading `/proc/*/stat` and `/proc/*/status`.
    /// Generates alerts for unknown processes or abnormal CPU usage.
    pub fn scan_processes(&self) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(err) => {
                warn!("security_daemon: cannot read /proc: {}", err);
                return alerts;
            }
        };

        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            // Only numeric directories (PIDs)
            if !name_str.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }

            let pid: u32 = match name_str.parse() {
                Ok(p) => p,
                Err(_) => continue,
            };

            let proc_name = match self.read_proc_name(pid) {
                Some(n) => n,
                None => continue,
            };

            // Check if this is an unknown process
            if !self.baselines.contains_key(&proc_name) {
                debug!("security_daemon: unknown process '{}' (pid {})", proc_name, pid);
                // Only alert for non-kernel threads (those with comm length > 0)
                if !proc_name.is_empty() {
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Info,
                        category: "process.unknown".into(),
                        message: format!("Unknown process detected: {} (pid {})", proc_name, pid),
                        timestamp: Utc::now(),
                        process: Some(proc_name.clone()),
                    });
                }
            }

            // Read CPU usage from /proc/<pid>/stat and compare to baseline
            if let Some(cpu_ticks) = self.read_proc_cpu(pid) {
                if let Some(baseline) = self.baselines.get(&proc_name) {
                    if baseline.avg_cpu > 0.0 && cpu_ticks > baseline.avg_cpu * 3.0 {
                        alerts.push(SecurityAlert {
                            severity: AlertSeverity::Warning,
                            category: "process.cpu_anomaly".into(),
                            message: format!(
                                "Process '{}' (pid {}) CPU {:.0} exceeds 3x baseline {:.0}",
                                proc_name, pid, cpu_ticks, baseline.avg_cpu
                            ),
                            timestamp: Utc::now(),
                            process: Some(proc_name.clone()),
                        });
                    }
                }
            }
        }

        alerts
    }

    /// Read process name from `/proc/<pid>/status`.
    fn read_proc_name(&self, pid: u32) -> Option<String> {
        let path = format!("/proc/{}/status", pid);
        let contents = fs::read_to_string(&path).ok()?;
        for line in contents.lines() {
            if line.starts_with("Name:") {
                return Some(line.split_whitespace().nth(1)?.to_string());
            }
        }
        None
    }

    /// Read total CPU ticks (utime + stime) from `/proc/<pid>/stat`.
    fn read_proc_cpu(&self, pid: u32) -> Option<f64> {
        let path = format!("/proc/{}/stat", pid);
        let contents = fs::read_to_string(&path).ok()?;
        let fields: Vec<&str> = contents.split_whitespace().collect();
        // Fields 13 and 14 are utime and stime (0-indexed)
        if fields.len() > 14 {
            let utime: f64 = fields[13].parse().ok()?;
            let stime: f64 = fields[14].parse().ok()?;
            Some(utime + stime)
        } else {
            None
        }
    }

    // -----------------------------------------------------------------------
    // Network scanning
    // -----------------------------------------------------------------------

    /// Scan network connections using `ss -tnp` and check for suspicious activity.
    pub fn scan_network(&self) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let output = match Command::new("ss").args(["-tnp"]).output() {
            Ok(o) => o,
            Err(err) => {
                warn!("security_daemon: cannot run ss: {}", err);
                return alerts;
            }
        };

        let stdout = String::from_utf8_lossy(&output.stdout);

        for line in stdout.lines().skip(1) {
            // Skip header
            let fields: Vec<&str> = line.split_whitespace().collect();
            if fields.len() < 5 {
                continue;
            }

            let state = fields[0];
            let local_addr = fields[3];
            let peer_addr = fields[4];

            // Extract port from address (addr:port format)
            let peer_port = Self::extract_port(peer_addr);
            let local_port = Self::extract_port(local_addr);

            // Check for mining pool port connections
            if let Some(port) = peer_port {
                if MINING_PORTS.contains(&port) {
                    let process_name = fields.get(5).map(|s| s.to_string());
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Critical,
                        category: "network.mining_port".into(),
                        message: format!(
                            "Connection to known mining port {} detected: {} -> {}",
                            port, local_addr, peer_addr
                        ),
                        timestamp: Utc::now(),
                        process: process_name,
                    });
                }
            }

            // Check for new listening ports not in whitelist
            if state == "LISTEN" {
                if let Some(port) = local_port {
                    if !self.port_whitelist.contains(&port) {
                        let process_name = fields.get(5).map(|s| s.to_string());
                        alerts.push(SecurityAlert {
                            severity: AlertSeverity::Warning,
                            category: "network.new_listener".into(),
                            message: format!(
                                "New listening port {} not in whitelist ({})",
                                port, local_addr
                            ),
                            timestamp: Utc::now(),
                            process: process_name,
                        });
                    }
                }
            }
        }

        alerts
    }

    /// Extract port number from "addr:port" or "[addr]:port" format.
    fn extract_port(addr: &str) -> Option<u16> {
        addr.rsplit(':').next()?.parse().ok()
    }

    // -----------------------------------------------------------------------
    // File integrity scanning
    // -----------------------------------------------------------------------

    /// Scan critical files for integrity changes using SHA-256.
    pub fn scan_file_integrity(&mut self, paths: &[&str]) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let check_paths = if paths.is_empty() {
            DEFAULT_INTEGRITY_PATHS
        } else {
            paths
        };

        for path in check_paths {
            let current_hash = match Self::sha256_file(path) {
                Ok(h) => h,
                Err(_) => {
                    debug!("security_daemon: cannot hash {}", path);
                    continue;
                }
            };

            if let Some(stored) = self.file_hashes.get(*path) {
                if *stored != current_hash {
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Critical,
                        category: "integrity.file_changed".into(),
                        message: format!("File integrity change detected: {}", path),
                        timestamp: Utc::now(),
                        process: None,
                    });
                }
            }

            // Update stored hash
            self.file_hashes.insert(path.to_string(), current_hash);
        }

        alerts
    }

    /// Compute SHA-256 hash of a file.
    fn sha256_file(path: &str) -> Result<String> {
        let contents = fs::read(path)?;
        let mut hasher = Sha256::new();
        hasher.update(&contents);
        Ok(format!("{:x}", hasher.finalize()))
    }

    // -----------------------------------------------------------------------
    // Baseline management
    // -----------------------------------------------------------------------

    /// Sample current process stats and update baselines (exponential moving average).
    pub fn update_baselines(&mut self) {
        let entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(_) => return,
        };

        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if !name_str.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }

            let pid: u32 = match name_str.parse() {
                Ok(p) => p,
                Err(_) => continue,
            };

            let proc_name = match self.read_proc_name(pid) {
                Some(n) => n,
                None => continue,
            };

            let cpu = self.read_proc_cpu(pid).unwrap_or(0.0);

            let baseline = self
                .baselines
                .entry(proc_name.clone())
                .or_insert_with(|| ProcessBaseline {
                    pid,
                    name: proc_name,
                    avg_cpu: 0.0,
                    avg_mem: 0.0,
                    avg_net_bytes: 0,
                    sample_count: 0,
                });

            baseline.sample_count += 1;
            let n = baseline.sample_count as f64;
            // Exponential moving average
            baseline.avg_cpu = baseline.avg_cpu + (cpu - baseline.avg_cpu) / n;
            baseline.pid = pid; // Track latest PID
        }
    }

    // -----------------------------------------------------------------------
    // Self-healing: service restart
    // -----------------------------------------------------------------------

    /// Restart a user-level systemd service after capturing recent logs.
    ///
    /// Only `--user` services are allowed (never system services).
    pub fn self_heal_service(service_name: &str) -> Result<String> {
        // Validate service name: reject empty, path-traversal, or suspicious chars.
        if service_name.is_empty()
            || service_name.contains('/')
            || service_name.contains("..")
            || service_name.contains(';')
            || service_name.contains('&')
        {
            anyhow::bail!("Invalid service name: {}", service_name);
        }

        // Capture recent logs (last 5 minutes, up to 20 lines).
        let log_output = Command::new("journalctl")
            .args([
                "--user",
                "-u",
                service_name,
                "--since",
                "5 min ago",
                "-n",
                "20",
                "--no-pager",
            ])
            .output();

        let last_lines = match log_output {
            Ok(out) => {
                let stdout = String::from_utf8_lossy(&out.stdout);
                let stderr = String::from_utf8_lossy(&out.stderr);
                if stdout.trim().is_empty() {
                    format!("(no recent logs; stderr: {})", stderr.trim())
                } else {
                    stdout.trim().to_string()
                }
            }
            Err(e) => format!("(failed to read logs: {})", e),
        };

        // Attempt restart via systemctl --user.
        let restart = Command::new("systemctl")
            .args(["--user", "restart", service_name])
            .output();

        match restart {
            Ok(out) if out.status.success() => Ok(format!(
                "Service '{}' was down. Logs:\n{}\nRestarted successfully.",
                service_name, last_lines
            )),
            Ok(out) => {
                let stderr = String::from_utf8_lossy(&out.stderr);
                anyhow::bail!(
                    "Failed to restart '{}': {}. Logs:\n{}",
                    service_name,
                    stderr.trim(),
                    last_lines
                )
            }
            Err(e) => anyhow::bail!(
                "Cannot execute systemctl for '{}': {}. Logs:\n{}",
                service_name,
                e,
                last_lines
            ),
        }
    }

    // -----------------------------------------------------------------------
    // Self-healing: disk cleanup
    // -----------------------------------------------------------------------

    /// Check disk usage on `/var` and the home directory.
    /// If usage exceeds 90%, automatically vacuum journal logs and remove
    /// unused Flatpak runtimes to reclaim space.
    pub fn self_heal_disk() -> Result<String> {
        let mut report = String::new();

        // Parse disk usage from `df` for the given mount point.
        fn disk_usage_pct(path: &str) -> Option<u8> {
            let output = Command::new("df")
                .args(["--output=pcent", path])
                .output()
                .ok()?;
            let stdout = String::from_utf8_lossy(&output.stdout);
            // Output looks like: "Use%\n  42%\n"
            for line in stdout.lines().skip(1) {
                let trimmed = line.trim().trim_end_matches('%');
                if let Ok(pct) = trimmed.parse::<u8>() {
                    return Some(pct);
                }
            }
            None
        }

        let home = std::env::var("HOME").unwrap_or_else(|_| "/var/home/lifeos".to_string());
        let var_pct = disk_usage_pct("/var");
        let home_pct = disk_usage_pct(&home);

        report.push_str(&format!(
            "Disk usage: /var={}%, home={}%\n",
            var_pct.map_or("??".to_string(), |p| p.to_string()),
            home_pct.map_or("??".to_string(), |p| p.to_string()),
        ));

        let needs_cleanup = var_pct.is_some_and(|p| p > 90)
            || home_pct.is_some_and(|p| p > 90);

        if !needs_cleanup {
            report.push_str("No cleanup needed (usage <= 90%).");
            return Ok(report);
        }

        report.push_str("Usage > 90% detected. Running auto-cleanup...\n");

        // 1) Vacuum journal logs.
        let journal_result = Command::new("journalctl")
            .args(["--vacuum-time=3d", "--vacuum-size=200M"])
            .output();
        match journal_result {
            Ok(out) => {
                let stdout = String::from_utf8_lossy(&out.stdout);
                let stderr = String::from_utf8_lossy(&out.stderr);
                report.push_str(&format!(
                    "Journal vacuum: {}{}\n",
                    stdout.trim(),
                    if stderr.trim().is_empty() {
                        String::new()
                    } else {
                        format!(" ({})", stderr.trim())
                    }
                ));
            }
            Err(e) => report.push_str(&format!("Journal vacuum failed: {}\n", e)),
        }

        // 2) Check for unused Flatpak runtimes.
        let flatpak_list = Command::new("flatpak")
            .args(["list", "--unused", "--columns=application"])
            .output();
        match flatpak_list {
            Ok(out) if out.status.success() => {
                let stdout = String::from_utf8_lossy(&out.stdout);
                let unused: Vec<&str> = stdout
                    .lines()
                    .filter(|l| !l.trim().is_empty())
                    .collect();
                if unused.is_empty() {
                    report.push_str("No unused Flatpak runtimes found.\n");
                } else {
                    report.push_str(&format!(
                        "Found {} unused Flatpak runtimes. Removing...\n",
                        unused.len()
                    ));
                    let remove = Command::new("flatpak")
                        .args(["uninstall", "--unused", "-y"])
                        .output();
                    match remove {
                        Ok(r) if r.status.success() => {
                            report.push_str("Unused Flatpak runtimes removed.\n");
                        }
                        Ok(r) => {
                            let stderr = String::from_utf8_lossy(&r.stderr);
                            report.push_str(&format!(
                                "Flatpak removal partial: {}\n",
                                stderr.trim()
                            ));
                        }
                        Err(e) => {
                            report.push_str(&format!("Flatpak removal failed: {}\n", e));
                        }
                    }
                }
            }
            Ok(_) => report.push_str("Flatpak list --unused returned an error.\n"),
            Err(_) => report.push_str("Flatpak not available.\n"),
        }

        // 3) Report post-cleanup usage.
        let var_after = disk_usage_pct("/var");
        let home_after = disk_usage_pct(&home);
        report.push_str(&format!(
            "Post-cleanup: /var={}%, home={}%\n",
            var_after.map_or("??".to_string(), |p| p.to_string()),
            home_after.map_or("??".to_string(), |p| p.to_string()),
        ));

        // Calculate freed space.
        if let (Some(before), Some(after)) = (var_pct, var_after) {
            if before > after {
                report.push_str(&format!(
                    "Freed ~{}% on /var.\n",
                    before.saturating_sub(after)
                ));
            }
        }

        Ok(report)
    }

    // -----------------------------------------------------------------------
    // Self-healing: network diagnostics
    // -----------------------------------------------------------------------

    /// Run network diagnostics: check DNS resolution, default gateway, and
    /// attempt fallback DNS if resolution fails.
    pub fn self_heal_network() -> Result<String> {
        let mut report = String::new();

        // 1) Check DNS resolution via getent.
        let dns_check = Command::new("getent")
            .args(["hosts", "dns.google"])
            .output();

        let dns_ok = match &dns_check {
            Ok(out) if out.status.success() => {
                let resolved = String::from_utf8_lossy(&out.stdout);
                report.push_str(&format!("DNS resolution OK: {}\n", resolved.trim()));
                true
            }
            Ok(out) => {
                let stderr = String::from_utf8_lossy(&out.stderr);
                report.push_str(&format!(
                    "DNS resolution FAILED for dns.google: {}\n",
                    stderr.trim()
                ));
                false
            }
            Err(e) => {
                report.push_str(&format!("Cannot execute getent: {}\n", e));
                false
            }
        };

        // 2) If DNS failed, attempt to set fallback nameservers.
        if !dns_ok {
            report.push_str("Attempting fallback DNS (8.8.8.8, 1.1.1.1)...\n");
            let fallback_content = "# LifeOS fallback DNS\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n";
            match fs::write("/etc/resolv.conf", fallback_content) {
                Ok(_) => {
                    report.push_str("Wrote fallback DNS to /etc/resolv.conf.\n");
                    // Verify fix.
                    let recheck = Command::new("getent")
                        .args(["hosts", "dns.google"])
                        .output();
                    match recheck {
                        Ok(out) if out.status.success() => {
                            report.push_str("DNS resolution restored after fallback.\n");
                        }
                        _ => {
                            report.push_str(
                                "DNS still failing after fallback. Network may be down.\n",
                            );
                        }
                    }
                }
                Err(e) => {
                    report.push_str(&format!(
                        "Cannot write /etc/resolv.conf (read-only on bootc?): {}\n",
                        e
                    ));
                }
            }
        }

        // 3) Check default gateway.
        let gw_output = Command::new("ip")
            .args(["route", "show", "default"])
            .output();
        match gw_output {
            Ok(out) if out.status.success() => {
                let stdout = String::from_utf8_lossy(&out.stdout);
                if stdout.trim().is_empty() {
                    report.push_str("WARNING: No default gateway found.\n");
                } else {
                    report.push_str(&format!("Default gateway: {}\n", stdout.trim()));
                }
            }
            Ok(out) => {
                let stderr = String::from_utf8_lossy(&out.stderr);
                report.push_str(&format!("ip route error: {}\n", stderr.trim()));
            }
            Err(e) => {
                report.push_str(&format!("Cannot execute 'ip': {}\n", e));
            }
        }

        Ok(report)
    }

    // -----------------------------------------------------------------------
    // Predictive maintenance
    // -----------------------------------------------------------------------

    /// Inspect hardware health (SSD SMART data, battery) and generate
    /// predictive warnings before failures occur.
    pub fn predictive_maintenance(&self) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        // --- SSD SMART via smartctl ---
        // Try to find the first NVMe device.
        let nvme_device = Self::find_first_nvme().unwrap_or_else(|| "/dev/nvme0n1".to_string());

        let smart_output = Command::new("smartctl")
            .args(["-j", "-a", &nvme_device])
            .output();

        match smart_output {
            Ok(out) if out.status.success() || !out.stdout.is_empty() => {
                let stdout = String::from_utf8_lossy(&out.stdout);
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&stdout) {
                    // percentage_used from NVMe health
                    let pct_used = json
                        .pointer("/nvme_smart_health_information_log/percentage_used")
                        .and_then(|v| v.as_u64());

                    if let Some(pct) = pct_used {
                        if pct > 80 {
                            // Rough estimate: if 80% used over N years, remaining ~ (100-pct)/(pct/assumed_age)
                            let remaining_months = if pct >= 100 {
                                0u64
                            } else {
                                // Assume ~3 years average age; estimate linearly
                                ((100 - pct) as f64 / pct as f64 * 36.0) as u64
                            };
                            alerts.push(SecurityAlert {
                                severity: AlertSeverity::Warning,
                                category: "hardware.ssd_wear".into(),
                                message: format!(
                                    "SSD has {}% life used. Plan replacement in ~{} months.",
                                    pct, remaining_months
                                ),
                                timestamp: Utc::now(),
                                process: None,
                            });
                        }
                    }

                    // media_errors
                    let media_errors = json
                        .pointer("/nvme_smart_health_information_log/media_errors")
                        .and_then(|v| v.as_u64());

                    if let Some(errors) = media_errors {
                        if errors > 0 {
                            alerts.push(SecurityAlert {
                                severity: AlertSeverity::Critical,
                                category: "hardware.ssd_errors".into(),
                                message: format!(
                                    "SSD has {} uncorrectable media error(s). Backup immediately.",
                                    errors
                                ),
                                timestamp: Utc::now(),
                                process: None,
                            });
                        }
                    }
                } else {
                    debug!("predictive_maintenance: failed to parse smartctl JSON");
                }
            }
            Ok(_) => {
                debug!("predictive_maintenance: smartctl returned no data for {}", nvme_device);
            }
            Err(e) => {
                debug!("predictive_maintenance: smartctl not available: {}", e);
            }
        }

        // --- Battery health ---
        let bat_full = fs::read_to_string("/sys/class/power_supply/BAT0/energy_full");
        let bat_design = fs::read_to_string("/sys/class/power_supply/BAT0/energy_full_design");

        if let (Ok(full_str), Ok(design_str)) = (bat_full, bat_design) {
            let full: f64 = full_str.trim().parse().unwrap_or(0.0);
            let design: f64 = design_str.trim().parse().unwrap_or(1.0);
            if design > 0.0 {
                let health_pct = (full / design * 100.0) as u8;
                if health_pct < 80 {
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Warning,
                        category: "hardware.battery".into(),
                        message: format!("Battery degraded to {}% of design capacity.", health_pct),
                        timestamp: Utc::now(),
                        process: None,
                    });
                }
            }
        }

        alerts
    }

    /// Find the first NVMe block device by scanning /dev/nvme*.
    fn find_first_nvme() -> Option<String> {
        let output = Command::new("ls")
            .args(["/dev/"])
            .output()
            .ok()?;
        let stdout = String::from_utf8_lossy(&output.stdout);
        for entry in stdout.lines() {
            let entry = entry.trim();
            // Match nvme0n1, nvme1n1, etc. (block device, not partition)
            if entry.starts_with("nvme")
                && entry.contains('n')
                && !entry.contains('p')
                && entry.len() > 5
            {
                return Some(format!("/dev/{}", entry));
            }
        }
        None
    }

    // -----------------------------------------------------------------------
    // Zero-day protection
    // -----------------------------------------------------------------------

    /// Compare running processes against known baselines.
    ///
    /// - New processes running for less than 5 minutes trigger an info alert.
    /// - Unknown processes with network connections trigger a warning.
    pub fn zero_day_protection(&self) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(_) => return alerts,
        };

        // Gather the set of processes with network connections (from ss).
        let net_procs = Self::processes_with_network();

        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if !name_str.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }

            let pid: u32 = match name_str.parse() {
                Ok(p) => p,
                Err(_) => continue,
            };

            let proc_name = match self.read_proc_name(pid) {
                Some(n) => n,
                None => continue,
            };

            // Skip if already in baseline.
            if self.baselines.contains_key(&proc_name) {
                continue;
            }

            // Check process age (uptime since boot vs process start time).
            let young = Self::is_process_young(pid, 300); // 5 minutes = 300 seconds

            if young {
                alerts.push(SecurityAlert {
                    severity: AlertSeverity::Info,
                    category: "zeroday.new_process".into(),
                    message: format!(
                        "New unknown process: {} (pid {}). Monitoring.",
                        proc_name, pid
                    ),
                    timestamp: Utc::now(),
                    process: Some(proc_name.clone()),
                });
            }

            // Check if this unknown process has network connections.
            if net_procs.contains(&pid) || net_procs.contains(&0) && net_procs.contains(&pid) {
                alerts.push(SecurityAlert {
                    severity: AlertSeverity::Warning,
                    category: "zeroday.network_unknown".into(),
                    message: format!(
                        "Unknown process '{}' (pid {}) has network connections. Isolating recommended.",
                        proc_name, pid
                    ),
                    timestamp: Utc::now(),
                    process: Some(proc_name),
                });
            }
        }

        alerts
    }

    /// Check if a process started less than `max_age_secs` seconds ago.
    fn is_process_young(pid: u32, max_age_secs: u64) -> bool {
        // Read system uptime.
        let uptime: f64 = match fs::read_to_string("/proc/uptime") {
            Ok(s) => s.split_whitespace().next().and_then(|v| v.parse().ok()).unwrap_or(0.0),
            Err(_) => return false,
        };

        // Read process start time (field 21, 0-indexed) in clock ticks.
        let stat = match fs::read_to_string(format!("/proc/{}/stat", pid)) {
            Ok(s) => s,
            Err(_) => return false,
        };
        let fields: Vec<&str> = stat.split_whitespace().collect();
        if fields.len() <= 21 {
            return false;
        }
        let start_ticks: f64 = match fields[21].parse() {
            Ok(v) => v,
            Err(_) => return false,
        };

        // Clock ticks per second (usually 100 on Linux).
        let ticks_per_sec: f64 = 100.0; // sysconf(_SC_CLK_TCK) default
        let process_start_secs = start_ticks / ticks_per_sec;
        let process_age = uptime - process_start_secs;

        process_age >= 0.0 && process_age < max_age_secs as f64
    }

    /// Gather set of PIDs that have active network connections (via `ss -tnp`).
    fn processes_with_network() -> std::collections::HashSet<u32> {
        let mut pids = std::collections::HashSet::new();

        let output = match Command::new("ss").args(["-tnp"]).output() {
            Ok(o) => o,
            Err(_) => return pids,
        };

        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines().skip(1) {
            // Look for pid=NNNN in the users: column
            // Format example: users:(("firefox",pid=1234,fd=56))
            if let Some(pid_start) = line.find("pid=") {
                let after_pid = &line[pid_start + 4..];
                let pid_str: String = after_pid.chars().take_while(|c| c.is_ascii_digit()).collect();
                if let Ok(pid) = pid_str.parse::<u32>() {
                    pids.insert(pid);
                }
            }
        }

        pids
    }

    // -----------------------------------------------------------------------
    // Status summary
    // -----------------------------------------------------------------------

    /// Get a serializable summary of the security daemon state.
    pub fn get_status(&self) -> SecurityStatus {
        SecurityStatus {
            baselines_count: self.baselines.len(),
            tracked_files: self.file_hashes.len(),
            whitelisted_ports: self.port_whitelist.clone(),
        }
    }
}

/// Serializable summary of the security daemon state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityStatus {
    pub baselines_count: usize,
    pub tracked_files: usize,
    pub whitelisted_ports: Vec<u16>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_daemon() {
        let daemon = SecurityDaemon::new();
        assert!(daemon.baselines.is_empty());
        assert!(daemon.file_hashes.is_empty());
        assert!(!daemon.port_whitelist.is_empty());
    }

    #[test]
    fn test_whitelist_port() {
        let mut daemon = SecurityDaemon::new();
        daemon.whitelist_port(9090);
        assert!(daemon.port_whitelist.contains(&9090));
        // No duplicates
        daemon.whitelist_port(9090);
        assert_eq!(
            daemon.port_whitelist.iter().filter(|&&p| p == 9090).count(),
            1
        );
    }

    #[test]
    fn test_extract_port() {
        assert_eq!(SecurityDaemon::extract_port("127.0.0.1:8081"), Some(8081));
        assert_eq!(SecurityDaemon::extract_port("[::1]:443"), Some(443));
        assert_eq!(SecurityDaemon::extract_port("*:22"), Some(22));
    }

    #[test]
    fn test_get_status() {
        let daemon = SecurityDaemon::new();
        let status = daemon.get_status();
        assert_eq!(status.baselines_count, 0);
        assert_eq!(status.tracked_files, 0);
    }

    #[test]
    fn test_scan_processes_runs() {
        // Should not panic even with empty baselines
        let daemon = SecurityDaemon::new();
        let _alerts = daemon.scan_processes();
    }

    #[test]
    fn test_update_baselines_runs() {
        let mut daemon = SecurityDaemon::new();
        daemon.update_baselines();
        // After update, we should have some baselines (on any Linux system)
        // In CI, /proc exists so this should populate
        assert!(daemon.baselines.len() > 0 || cfg!(not(target_os = "linux")));
    }

    #[test]
    fn test_self_heal_service_rejects_invalid_names() {
        assert!(SecurityDaemon::self_heal_service("").is_err());
        assert!(SecurityDaemon::self_heal_service("../etc/passwd").is_err());
        assert!(SecurityDaemon::self_heal_service("foo;bar").is_err());
        assert!(SecurityDaemon::self_heal_service("foo&bar").is_err());
    }

    #[test]
    fn test_self_heal_disk_runs() {
        // Should not panic; may report unknown percentages in CI.
        let result = SecurityDaemon::self_heal_disk();
        assert!(result.is_ok());
        let report = result.unwrap();
        assert!(report.contains("Disk usage"));
    }

    #[test]
    fn test_self_heal_network_runs() {
        // Should not panic even without network.
        let result = SecurityDaemon::self_heal_network();
        assert!(result.is_ok());
    }

    #[test]
    fn test_predictive_maintenance_runs() {
        let daemon = SecurityDaemon::new();
        // Should not panic; may return empty if no hardware sensors.
        let _alerts = daemon.predictive_maintenance();
    }

    #[test]
    fn test_zero_day_protection_runs() {
        let daemon = SecurityDaemon::new();
        // With empty baselines, most processes will be flagged.
        let alerts = daemon.zero_day_protection();
        // On a Linux system with /proc, we should get some alerts.
        assert!(!alerts.is_empty() || cfg!(not(target_os = "linux")));
    }

    #[test]
    fn test_is_process_young() {
        // PID 1 (init) should NOT be young on any running system.
        assert!(!SecurityDaemon::is_process_young(1, 300));
        // Non-existent PID should return false.
        assert!(!SecurityDaemon::is_process_young(999_999_999, 300));
    }

    #[test]
    fn test_processes_with_network() {
        // Should not panic; returns a set (possibly empty in sandboxed CI).
        let pids = SecurityDaemon::processes_with_network();
        // Just verify it's a valid set.
        let _ = pids.len();
    }

    #[test]
    fn test_find_first_nvme() {
        // May return None in CI without NVMe devices; should not panic.
        let _device = SecurityDaemon::find_first_nvme();
    }
}
