//! AI Security Daemon (Fase Y)
//!
//! Process and network monitoring with anomaly detection.
//! Scans for suspicious activity: crypto-mining ports, unexpected processes,
//! file integrity changes, and resource abuse.

use anyhow::Result;
use chrono::{DateTime, Utc};
use log::{debug, warn};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fs;
use std::process::Command;

/// Severity levels for security alerts.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
}

/// A security alert generated by a scan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityAlert {
    pub severity: AlertSeverity,
    pub category: String,
    pub message: String,
    pub timestamp: DateTime<Utc>,
    pub process: Option<String>,
}

/// Baseline statistics for a known process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessBaseline {
    pub pid: u32,
    pub name: String,
    pub avg_cpu: f64,
    pub avg_mem: f64,
    pub avg_net_bytes: u64,
    pub sample_count: u64,
}

/// Known crypto-mining pool ports.
const MINING_PORTS: &[u16] = &[3333, 4444, 5555, 8333, 14444];

/// Default critical files to monitor for integrity.
const DEFAULT_INTEGRITY_PATHS: &[&str] = &["/etc/passwd", "/etc/shadow", "/etc/sudoers"];

/// AI Security daemon that monitors processes, network, and file integrity.
#[derive(Debug)]
pub struct SecurityDaemon {
    /// Per-process-name baselines (keyed by process name).
    baselines: HashMap<String, ProcessBaseline>,
    /// Stored SHA-256 hashes for file integrity checks.
    file_hashes: HashMap<String, String>,
    /// Whitelisted listening ports.
    port_whitelist: Vec<u16>,
}

impl SecurityDaemon {
    /// Create a new security daemon with empty baselines.
    pub fn new() -> Self {
        Self {
            baselines: HashMap::new(),
            file_hashes: HashMap::new(),
            // Common whitelisted ports: SSH, HTTP API, llama-server
            port_whitelist: vec![22, 8080, 8081, 8082],
        }
    }

    /// Add a port to the whitelist of expected listening ports.
    pub fn whitelist_port(&mut self, port: u16) {
        if !self.port_whitelist.contains(&port) {
            self.port_whitelist.push(port);
        }
    }

    // -----------------------------------------------------------------------
    // Process scanning
    // -----------------------------------------------------------------------

    /// Scan running processes by reading `/proc/*/stat` and `/proc/*/status`.
    /// Generates alerts for unknown processes or abnormal CPU usage.
    pub fn scan_processes(&self) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(err) => {
                warn!("security_daemon: cannot read /proc: {}", err);
                return alerts;
            }
        };

        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            // Only numeric directories (PIDs)
            if !name_str.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }

            let pid: u32 = match name_str.parse() {
                Ok(p) => p,
                Err(_) => continue,
            };

            let proc_name = match self.read_proc_name(pid) {
                Some(n) => n,
                None => continue,
            };

            // Check if this is an unknown process
            if !self.baselines.contains_key(&proc_name) {
                debug!("security_daemon: unknown process '{}' (pid {})", proc_name, pid);
                // Only alert for non-kernel threads (those with comm length > 0)
                if !proc_name.is_empty() {
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Info,
                        category: "process.unknown".into(),
                        message: format!("Unknown process detected: {} (pid {})", proc_name, pid),
                        timestamp: Utc::now(),
                        process: Some(proc_name.clone()),
                    });
                }
            }

            // Read CPU usage from /proc/<pid>/stat and compare to baseline
            if let Some(cpu_ticks) = self.read_proc_cpu(pid) {
                if let Some(baseline) = self.baselines.get(&proc_name) {
                    if baseline.avg_cpu > 0.0 && cpu_ticks > baseline.avg_cpu * 3.0 {
                        alerts.push(SecurityAlert {
                            severity: AlertSeverity::Warning,
                            category: "process.cpu_anomaly".into(),
                            message: format!(
                                "Process '{}' (pid {}) CPU {:.0} exceeds 3x baseline {:.0}",
                                proc_name, pid, cpu_ticks, baseline.avg_cpu
                            ),
                            timestamp: Utc::now(),
                            process: Some(proc_name.clone()),
                        });
                    }
                }
            }
        }

        alerts
    }

    /// Read process name from `/proc/<pid>/status`.
    fn read_proc_name(&self, pid: u32) -> Option<String> {
        let path = format!("/proc/{}/status", pid);
        let contents = fs::read_to_string(&path).ok()?;
        for line in contents.lines() {
            if line.starts_with("Name:") {
                return Some(line.split_whitespace().nth(1)?.to_string());
            }
        }
        None
    }

    /// Read total CPU ticks (utime + stime) from `/proc/<pid>/stat`.
    fn read_proc_cpu(&self, pid: u32) -> Option<f64> {
        let path = format!("/proc/{}/stat", pid);
        let contents = fs::read_to_string(&path).ok()?;
        let fields: Vec<&str> = contents.split_whitespace().collect();
        // Fields 13 and 14 are utime and stime (0-indexed)
        if fields.len() > 14 {
            let utime: f64 = fields[13].parse().ok()?;
            let stime: f64 = fields[14].parse().ok()?;
            Some(utime + stime)
        } else {
            None
        }
    }

    // -----------------------------------------------------------------------
    // Network scanning
    // -----------------------------------------------------------------------

    /// Scan network connections using `ss -tnp` and check for suspicious activity.
    pub fn scan_network(&self) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let output = match Command::new("ss").args(["-tnp"]).output() {
            Ok(o) => o,
            Err(err) => {
                warn!("security_daemon: cannot run ss: {}", err);
                return alerts;
            }
        };

        let stdout = String::from_utf8_lossy(&output.stdout);

        for line in stdout.lines().skip(1) {
            // Skip header
            let fields: Vec<&str> = line.split_whitespace().collect();
            if fields.len() < 5 {
                continue;
            }

            let state = fields[0];
            let local_addr = fields[3];
            let peer_addr = fields[4];

            // Extract port from address (addr:port format)
            let peer_port = Self::extract_port(peer_addr);
            let local_port = Self::extract_port(local_addr);

            // Check for mining pool port connections
            if let Some(port) = peer_port {
                if MINING_PORTS.contains(&port) {
                    let process_name = fields.get(5).map(|s| s.to_string());
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Critical,
                        category: "network.mining_port".into(),
                        message: format!(
                            "Connection to known mining port {} detected: {} -> {}",
                            port, local_addr, peer_addr
                        ),
                        timestamp: Utc::now(),
                        process: process_name,
                    });
                }
            }

            // Check for new listening ports not in whitelist
            if state == "LISTEN" {
                if let Some(port) = local_port {
                    if !self.port_whitelist.contains(&port) {
                        let process_name = fields.get(5).map(|s| s.to_string());
                        alerts.push(SecurityAlert {
                            severity: AlertSeverity::Warning,
                            category: "network.new_listener".into(),
                            message: format!(
                                "New listening port {} not in whitelist ({})",
                                port, local_addr
                            ),
                            timestamp: Utc::now(),
                            process: process_name,
                        });
                    }
                }
            }
        }

        alerts
    }

    /// Extract port number from "addr:port" or "[addr]:port" format.
    fn extract_port(addr: &str) -> Option<u16> {
        addr.rsplit(':').next()?.parse().ok()
    }

    // -----------------------------------------------------------------------
    // File integrity scanning
    // -----------------------------------------------------------------------

    /// Scan critical files for integrity changes using SHA-256.
    pub fn scan_file_integrity(&mut self, paths: &[&str]) -> Vec<SecurityAlert> {
        let mut alerts = Vec::new();

        let check_paths = if paths.is_empty() {
            DEFAULT_INTEGRITY_PATHS
        } else {
            paths
        };

        for path in check_paths {
            let current_hash = match Self::sha256_file(path) {
                Ok(h) => h,
                Err(_) => {
                    debug!("security_daemon: cannot hash {}", path);
                    continue;
                }
            };

            if let Some(stored) = self.file_hashes.get(*path) {
                if *stored != current_hash {
                    alerts.push(SecurityAlert {
                        severity: AlertSeverity::Critical,
                        category: "integrity.file_changed".into(),
                        message: format!("File integrity change detected: {}", path),
                        timestamp: Utc::now(),
                        process: None,
                    });
                }
            }

            // Update stored hash
            self.file_hashes.insert(path.to_string(), current_hash);
        }

        alerts
    }

    /// Compute SHA-256 hash of a file.
    fn sha256_file(path: &str) -> Result<String> {
        let contents = fs::read(path)?;
        let mut hasher = Sha256::new();
        hasher.update(&contents);
        Ok(format!("{:x}", hasher.finalize()))
    }

    // -----------------------------------------------------------------------
    // Baseline management
    // -----------------------------------------------------------------------

    /// Sample current process stats and update baselines (exponential moving average).
    pub fn update_baselines(&mut self) {
        let entries = match fs::read_dir("/proc") {
            Ok(e) => e,
            Err(_) => return,
        };

        for entry in entries.flatten() {
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if !name_str.chars().all(|c| c.is_ascii_digit()) {
                continue;
            }

            let pid: u32 = match name_str.parse() {
                Ok(p) => p,
                Err(_) => continue,
            };

            let proc_name = match self.read_proc_name(pid) {
                Some(n) => n,
                None => continue,
            };

            let cpu = self.read_proc_cpu(pid).unwrap_or(0.0);

            let baseline = self
                .baselines
                .entry(proc_name.clone())
                .or_insert_with(|| ProcessBaseline {
                    pid,
                    name: proc_name,
                    avg_cpu: 0.0,
                    avg_mem: 0.0,
                    avg_net_bytes: 0,
                    sample_count: 0,
                });

            baseline.sample_count += 1;
            let n = baseline.sample_count as f64;
            // Exponential moving average
            baseline.avg_cpu = baseline.avg_cpu + (cpu - baseline.avg_cpu) / n;
            baseline.pid = pid; // Track latest PID
        }
    }

    // -----------------------------------------------------------------------
    // Status summary
    // -----------------------------------------------------------------------

    /// Get a serializable summary of the security daemon state.
    pub fn get_status(&self) -> SecurityStatus {
        SecurityStatus {
            baselines_count: self.baselines.len(),
            tracked_files: self.file_hashes.len(),
            whitelisted_ports: self.port_whitelist.clone(),
        }
    }
}

/// Serializable summary of the security daemon state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityStatus {
    pub baselines_count: usize,
    pub tracked_files: usize,
    pub whitelisted_ports: Vec<u16>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_daemon() {
        let daemon = SecurityDaemon::new();
        assert!(daemon.baselines.is_empty());
        assert!(daemon.file_hashes.is_empty());
        assert!(!daemon.port_whitelist.is_empty());
    }

    #[test]
    fn test_whitelist_port() {
        let mut daemon = SecurityDaemon::new();
        daemon.whitelist_port(9090);
        assert!(daemon.port_whitelist.contains(&9090));
        // No duplicates
        daemon.whitelist_port(9090);
        assert_eq!(
            daemon.port_whitelist.iter().filter(|&&p| p == 9090).count(),
            1
        );
    }

    #[test]
    fn test_extract_port() {
        assert_eq!(SecurityDaemon::extract_port("127.0.0.1:8081"), Some(8081));
        assert_eq!(SecurityDaemon::extract_port("[::1]:443"), Some(443));
        assert_eq!(SecurityDaemon::extract_port("*:22"), Some(22));
    }

    #[test]
    fn test_get_status() {
        let daemon = SecurityDaemon::new();
        let status = daemon.get_status();
        assert_eq!(status.baselines_count, 0);
        assert_eq!(status.tracked_files, 0);
    }

    #[test]
    fn test_scan_processes_runs() {
        // Should not panic even with empty baselines
        let daemon = SecurityDaemon::new();
        let _alerts = daemon.scan_processes();
    }

    #[test]
    fn test_update_baselines_runs() {
        let mut daemon = SecurityDaemon::new();
        daemon.update_baselines();
        // After update, we should have some baselines (on any Linux system)
        // In CI, /proc exists so this should populate
        assert!(daemon.baselines.len() > 0 || cfg!(not(target_os = "linux")));
    }
}
